export const KIND_LABELS = {
  cron: "Cron 定时",
  semver_range: "SemVer 范围",
  cidr: "CIDR 网络",
  uri: "URI",
  content_type: "Content-Type",
  iso_duration: "ISO 时长",
  rrule: "重复规则",
  unix_permission: "Unix 权限",
};

export const DIALECT_LABELS = {
  "unix-5": "Unix / Linux",
  "github-actions": "GitHub Actions",
};

export const FIELD_LABELS = {
  timezone: "时区",
  reference_time: "参考时间",
  count: "返回数量",
  candidate: "候选值",
  include_prerelease: "包含预发布版本",
  range: "另一个版本范围",
  address: "IP 地址",
  cidr: "另一个 CIDR",
  reference: "相对引用",
  uri: "另一个 URI",
  name: "参数名",
  subject: "权限主体",
  permission: "权限位",
  family: "地址族",
  scheme: "协议",
  userinfo: "用户信息",
  host: "主机",
  port: "端口",
  path: "路径",
  query: "查询参数",
  fragment: "片段",
  network: "网络地址",
  prefix: "前缀长度",
  netmask: "子网掩码",
  first_address: "首个地址",
  last_address: "末个地址",
  address_count: "地址数量",
  media_type: "媒体类型",
  type: "主类型",
  subtype: "子类型",
  suffix: "后缀",
  parameters: "参数",
  octal: "八进制",
  symbolic: "符号形式",
  special: "特殊位",
  classes: "权限分组",
  comparator_sets: "比较条件",
  minute: "分钟",
  hour: "小时",
  day_of_month: "日期",
  month: "月份",
  day_of_week: "星期",
  years: "年",
  months: "月",
  weeks: "周",
  days: "日",
  hours: "小时",
  minutes: "分钟",
  seconds: "秒",
  matches: "是否匹配",
  intersects: "是否相交",
  contains: "是否包含",
  overlaps: "是否重叠",
  resolved: "解析结果",
  equals: "是否等价",
  present: "是否存在",
  value: "值",
  allows: "是否允许",
  expression: "表达式",
  representation: "表示方式",
  operator: "比较符",
  version: "版本",
  owner: "所有者",
  group: "用户组",
  other: "其他用户",
  read: "读取",
  write: "写入",
  execute: "执行",
  setuid: "Setuid",
  setgid: "Setgid",
  sticky: "Sticky",
  frequency: "频率",
  interval: "间隔",
  until: "截止时间",
  week_start: "每周起始日",
  by_second: "秒筛选",
  by_minute: "分钟筛选",
  by_hour: "小时筛选",
  by_day: "星期筛选",
  by_month_day: "月内日期筛选",
  by_year_day: "年内日期筛选",
  by_week_number: "周数筛选",
  by_month: "月份筛选",
  by_set_position: "集合位置筛选",
  weekday: "星期",
  ordinal: "序数",
  bounded: "是否有终止边界",
  termination: "终止方式",
  day_of_month_day_of_week_relation: "日期与星期关系",
};

export const VALUE_LABELS = {
  family: { ipv4: "IPv4", ipv6: "IPv6" },
  day_of_month_day_of_week_relation: { or: "任一条件满足即可" },
  termination: { count: "次数", until: "截止时间", unbounded: "无界" },
};

export const DIAGNOSTIC_MESSAGES = {
  E_CRON_GITHUB_MIN_INTERVAL: "GitHub Actions 的定时间隔不能短于 5 分钟。",
  E_CRON_GITHUB_SYNTAX: "这不是 GitHub Actions 支持的五段 Cron 写法。",
  W_CRON_DOM_DOW_OR: "日期和星期都有限制时，满足任一条件就会运行。",
  W_CRON_PLATFORM_QUERY_LIMITED: "当前只能按 UTC 计算 GitHub Actions 的执行时间。",
  W_CIDR_HOST_BITS_CLEARED: "输入包含主机位；标准写法已归到对应网络地址。",
  W_URI_USERINFO: "URI 中含有用户信息；不宜在其中保存凭据。",
  W_DURATION_CALENDAR_CONTEXT: "年和月取决于具体日历，不能直接换算成固定秒数。",
};

export const EXAMPLES = {
  semver: { kind: "semver_range", dialect: "npm", expression: "^3.2.0" },
  cron: { kind: "cron", dialect: "unix-5", expression: "0 9 * * 1-5" },
  cidr: { kind: "cidr", dialect: "cidr", expression: "192.168.1.0/24" },
  permission: { kind: "unix_permission", dialect: "posix-mode", expression: "4755" },
};
