export const KIND_LABELS = {
  cron: "Cron 定时",
  semver_range: "SemVer 范围",
  cidr: "CIDR 网络",
  uri: "URI",
  content_type: "Content-Type",
  iso_duration: "ISO 时长",
  unix_permission: "Unix 权限",
};

export const KIND_SUMMARIES = {
  cron: "五段 Unix 与 GitHub Actions 定时规则。",
  semver_range: "npm 语义版本范围与版本匹配关系。",
  cidr: "IPv4 或 IPv6 网络、包含与重叠关系。",
  uri: "带 scheme 的 RFC 3986 URI、解析与等价比较。",
  content_type: "HTTP 媒体类型及其参数。",
  iso_duration: "ISO 8601 时长组成，不假定日历长度。",
  unix_permission: "八进制或符号形式的 Unix 权限。",
};

export const FIELD_LABELS = {
  timezone: "时区",
  reference_time: "参考时间",
  count: "返回数量",
  candidate: "候选值",
  include_prerelease: "包含预发布版本",
  range: "另一个版本范围",
  address: "IP 地址",
  cidr: "另一个 CIDR",
  reference: "相对引用",
  uri: "另一个 URI",
  name: "参数名",
  subject: "权限主体",
  permission: "权限位",
  family: "地址族",
  network: "网络地址",
  prefix: "前缀长度",
  netmask: "子网掩码",
  first_address: "首个地址",
  last_address: "末个地址",
  address_count: "地址数量",
  media_type: "媒体类型",
  subtype: "子类型",
  suffix: "后缀",
  parameters: "参数",
  octal: "八进制",
  symbolic: "符号形式",
  special: "特殊位",
  classes: "权限分组",
  comparator_sets: "比较条件",
  minute: "分钟",
  hour: "小时",
  day_of_month: "日期",
  month: "月份",
  day_of_week: "星期",
  years: "年",
  months: "月",
  weeks: "周",
  days: "日",
  hours: "小时",
  minutes: "分钟",
  seconds: "秒",
  matches: "是否匹配",
  intersects: "是否相交",
  contains: "是否包含",
  overlaps: "是否重叠",
  resolved: "解析结果",
  equals: "是否等价",
  present: "是否存在",
  value: "值",
  allows: "是否允许",
  expression: "表达式",
  representation: "表示方式",
  operator: "比较符",
  version: "版本",
  owner: "所有者",
  group: "用户组",
  other: "其他用户",
  read: "读取",
  write: "写入",
  execute: "执行",
  setuid: "Setuid",
  setgid: "Setgid",
  sticky: "Sticky",
};

export const QUERY_LABELS = {
  next_occurrences: "后续执行时间",
  matches: "是否匹配",
  intersects: "范围是否相交",
  contains: "是否包含地址",
  overlaps: "网络是否重叠",
  resolve: "解析相对引用",
  equals: "是否等价",
  parameter: "读取参数",
  allows: "检查权限",
};

export const EXAMPLES = {
  semver: { kind: "semver_range", dialect: "npm", expression: "^3.2.0" },
  cron: { kind: "cron", dialect: "unix-5", expression: "0 9 * * 1-5" },
  cidr: { kind: "cidr", dialect: "cidr", expression: "192.168.1.0/24" },
  permission: { kind: "unix_permission", dialect: "posix-mode", expression: "4755" },
};
